version : '3'
 
services:
  productsapi:
    image: productsapi
    ports:
      - 8082:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - connectionStrings__main=Data Source=192.168.56.1,1433; Initial Catalog=Products; User Id=DockerUser; Password=s[qfBKS/r((2Cg+m
    build:
      context: .
      dockerfile: ./Products.API/Dockerfile
    networks:
      - dotnetcorepromgrafana
      
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9091:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - dotnetcorepromgrafana

  grafana: 
    image: grafana/grafana
    #command:
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=P@ssw0rd
    restart: always
    ports:
      - 3000:3000
    networks:
      - dotnetcorepromgrafana

### put all the networks here
networks:
  dotnetcorepromgrafana: