version : '3'
 
services:

  mongo:
   image: mongo
   ports:
    - 27018:27017
   volumes:
    - mongo-data:/data/db
   networks:
    - quiesconetwork    

  # db:
    # image: microsoft/mssql-server-linux:latest
    # environment:
      # SA_PASSWORD: "SomePassword123"
      # ACCEPT_EULA: "Y"
    # ports:
      # - "5434:1433"
    # volumes:
     # - sql-data:/var/opt/mssql/data
    # networks:
     # - quiesconetwork

  elasticsearch:
    image: elasticsearch:7.9.3
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
        - "discovery.type=single-node"
    ports:
     - 9200:9200
     - 9300:9300
    networks:
     - quiesconetwork
      
  logstash:
    build:
      context: ./logstash
      dockerfile: ./logstash/Dockerfile
    container_name: logstash
    hostname: logstash
    ports:
     - 5001:5001
    volumes:
     - .\Logstash\Config:/usr/share/logstash/pipeline/
    links:
     - elasticsearch:elasticsearch
    depends_on:
     - elasticsearch
    networks:
     - quiesconetwork

### put all the networks here
networks:
  quiesconetwork:
  
volumes:
    sql-data:
    mongo-data: